name = "PyThermo"
uuid = "6fae04a5-42e9-4d0c-90a8-26d1a9434b6b"
authors = ["Alex Ames <alexander.m.ames@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
PyCall = "1.92"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
